config/routes.rb
Rails.application.routes.draw do

  resources :groups, only: [:show, :new, :create] do
    resources :recipes, only: [:index, :new, :create, :destroy]
    member do
      get 'add_user'
      post 'create_user'
      post 'balance_user'
    end
  end

  get 'groups/:id/history' => 'groups#history', as: :history

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  root 'welcome#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users, through: :memberships
  has_many :memberships
  has_many :recipes

  validates :name, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_user_in_group, only: [:show]

  expose(:group, attributes: :group_params)
  expose(:recipe)
  expose(:recipes)

  def new
  end

  def show
    group.users.each do |user|
      next if user == current_user
      amount = 0
      # every recipe members for recipes that I created and user is involved with
      additive_recipe_members = RecipeMember.joins("LEFT OUTER JOIN recipes ON recipes.id = recipe_members.recipe_id")
        .where("recipes.user_id = :current_user_id AND recipe_members.user_id = :user_id AND recipes.group_id = :group_id AND recipe_members.balance = FALSE",
            current_user_id: current_user.id,
            user_id: user.id,
            group_id: group.id)
      additive_recipe_members.each do |recipe_member|
        recipe = recipe_member.recipe
        # add one for current_user
        amount += recipe.amount / (recipe.recipe_members.count + 1)
      end
      # binding.pry
      subtraction_recipe_members = RecipeMember.joins("LEFT OUTER JOIN recipes ON recipes.id = recipe_members.recipe_id")
        .where("recipes.user_id = :user_id AND recipe_members.user_id = :current_user_id AND recipes.group_id = :group_id AND recipe_members.balance = FALSE",
          current_user_id: current_user.id,
          user_id: user.id,
          group_id: group.id)
      subtraction_recipe_members.each do |recipe_member|
        recipe = recipe_member.recipe
        # add one for user
        amount -= recipe.amount / (recipe.recipe_members.count + 1)
      end
      # now in amount I have proper value
      user.amount = amount
    end
  end


  def create
    if group.save
      group.users << current_user
      redirect_to group
      flash[:success] = 'Group was successfully created'
    else
      render :new
    end
  end

  def add_user
    @group = Group.find(params[:id])
    @user = User.new
  end

  def create_user
    @group = Group.find(params[:id])
    @user = User.find_by email: user_params[:email]
    if @user && !(@group.users.include?(@user))
      @group.users << @user
      redirect_to group_path(@group)
    else
      @user = User.new(user_params)
      @user.errors.add(:email, 'is not in database')
      render :add_user
    end
  end

  def balance_user
    user = User.find(params[:user_id])
    group = Group.find(params[:id])
    additive_recipe_members = RecipeMember.joins("LEFT OUTER JOIN recipes ON recipes.id = recipe_members.recipe_id")
      .where("recipes.user_id = :current_user_id AND recipe_members.user_id = :user_id AND recipes.group_id = :group_id AND recipe_members.balance = FALSE",
          current_user_id: current_user.id,
          user_id: user.id,
          group_id: group.id)
    subtraction_recipe_members = RecipeMember.joins("LEFT OUTER JOIN recipes ON recipes.id = recipe_members.recipe_id")
      .where("recipes.user_id = :user_id AND recipe_members.user_id = :current_user_id AND recipes.group_id = :group_id AND recipe_members.balance = FALSE",
        current_user_id: current_user.id,
        user_id: user.id,
        group_id: group.id)
    all_members = additive_recipe_members + subtraction_recipe_members
    all_members.map { |e| e.update_attributes(balance: true) }
    FrindsdebtsMailer.balance_email(user, group, current_user.email).deliver
    redirect_to group_path(group)
  end

  def history
    @recipe_members = RecipeMember.joins("LEFT OUTER JOIN recipes ON recipes.id = recipe_members.recipe_id").where("recipes.group_id = :group_id AND recipes.user_id = :current_user_id OR recipe_members.user_id = :current_user_id", current_user_id: current_user.id, group_id: group.id)
  end


  private

    def group_params
      params.require(:group).permit(:name)
    end

    def user_params
      params.require(:user).permit(:email)
    end

    def authenticate_user_in_group
      unless group.users.include? current_user
        redirect_to root_path
      end
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/add_user.html.haml
%h1
  = "Group #{@group.name}"
%h2 Adding new member:
= simple_form_for @user, url: create_user_group_path(@group), method: :post do |f|
  = f.error_notification
  .form-group
    = f.input :email, autofocus: true, placeholder: "Enter email", input_html: { class: 'form-control' }
  .form-group
    = f.button :submit, "Add", class: 'btn btn-default'

app/views/groups/create.html.haml
%h1 Groups#create
%p Find me in app/views/groups/create.html.haml

app/views/groups/history.html.haml
%h1.style{ style: 'text-align: center' }
  = "Group #{group.name}"

.panel.panel-default
  .panel-heading
    %h3.panel-title.style{ style: 'text-align: center' } History

  .panel-body
    %table.table
      %tr
        %th #
        %th Activity
        %th Action
      - @recipe_members.each.with_index(1) do |recipe_member, index|
        %tr
          %td= index
          - if recipe_member.user_id == current_user.id
            %td= recipe_member.recipe.user.email + " borrowed you for " + recipe_member.recipe.description
            %td
          - else
            %td= "You borrowed " + recipe_member.user.email + " for " + recipe_member.recipe.description
            %td= link_to "Remove the recipe", group_recipe_path(group, recipe_member.recipe), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure?" }
        

app/views/groups/new.html.haml
%h1
  = "Group #{group.name}"
%h2 Add new group:
= simple_form_for group do |f|
  = f.error_notification
  .form-group
    = f.input :name, autofocus: true, placeholder: "Enter name", input_html: { class: 'form-control' }
  .form-group
    = f.button :submit, "Add", class: 'btn btn-default'

app/views/groups/show.html.haml
%h1
  = "Group #{group.name}"
%p
  = link_to 'Add new recipe', new_group_recipe_path(group), class: 'btn btn-primary'

%table.table
  %tr
    %th Name:
    %th Money:
    %th Balance:
  -group.users.each do |user|
    - next if user == current_user
    %tr
      %td
        = user.email
      %td
        = user.amount
      %td
        - if user.amount != 0
          = button_to "Balance", { action: "balance_user", user_id: user.id }, data: { confirm: "Are you sure?" }, class: 'btn btn-primary'

%p
  = link_to 'Add new member',add_user_group_path, class: 'btn btn-primary'
  = link_to 'History',history_path, class: 'btn btn-primary'